security:
  ignore-vulnerabilities:
    67599:
      reason: pip won't fix it, because it is an intended behaviour
    71064:
      reason: the updated requests version is ony available for Python 3.8+
