from pathlib import Path

# General
HOME = str(Path.home())
CONFIG_DIRECTORY = '/.policy_sentry/'

# Database
DATABASE_FILE_NAME = 'aws.sqlite3'
DATABASE_FILE_PATH = HOME + CONFIG_DIRECTORY + DATABASE_FILE_NAME

# Boto
DEFAULT_CREDENTIALS_FILE = HOME + '/.aws/credentials'

# Policy constants
POLICY_LANGUAGE_VERSION = "2012-10-17"

# Audit functionality constants
AUDIT_DIRECTORY_FOLDER = 'audit/'
AUDIT_DIRECTORY_PATH = HOME + CONFIG_DIRECTORY + AUDIT_DIRECTORY_FOLDER
DEFAULT_AUDIT_FILE_NAME = '/privilege-escalation.txt'
DEFAULT_AUDIT_FILE_PATH = AUDIT_DIRECTORY_PATH + DEFAULT_AUDIT_FILE_NAME

# from policy_sentry.shared.constants import HOME, CONFIG_DIRECTORY, DATABASE_FILE_NAME, DATABASE_FILE_PATH, AUDIT_DIRECTORY_FOLDER, POLICY_LANGUAGE_VERSION
