name: Bump Version

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          ref: master

      - name: Bump version
        run: |
          version_file="policy_sentry/bin/version.py"

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --tags
          git pull origin master
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "latest tag: $latest_tag"
          new_tag=$(echo $latest_tag | awk -F. -v a="$1" -v b="$2" -v c="$3" '{printf("%d.%d.%d", $1+a, $2+b , $3+1)}')
          echo "new tag: $new_tag"

          printf "# pylint: disable=missing-module-docstring\n__version__ = \"$new_tag\"\n""" > $version_file

          git commit -m "Bump to ${new_tag}"  $version_file || echo "No changes to commit"
          git push origin
