# .github/workflows/test.yml

name: continuous-integration

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

env:
  JUST_VERSION: '1'
  PREK_VERSION: '0.4.x'
  TERRAFORM_VERSION: '1.13'

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          activate-environment: true
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4.0.0
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
        with:
          just-version: ${{ env.JUST_VERSION }}
      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # v2.0.4
        with:
          prek-version: ${{ env.PREK_VERSION }}

  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          activate-environment: true
      - run: uv sync --frozen

      - run: just build-package
      - run: just validate-sdist
      - run: just validate-wheel

  ci:
    needs: [prek, sanity]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          activate-environment: true
      - run: uv sync --frozen

      - run: just build-package
      - run: just unit-tests
      - run: just integration-tests

  python-version:
    needs: [prek, sanity]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix:
        python: ['3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
        with:
          python-version: ${{ matrix.python }}
          activate-environment: true
      - run: uv sync --frozen

      - run: just build-package
      - run: just unit-tests
      - run: just integration-tests
